
services:
  database: 
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_TCP_PORT=${DB_PORT}
    expose: 
    - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  --explicit_defaults_for_timestamp

  api: 
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes: 
      - ./src:/app/src
    expose:
    - ${PORT}
    ports: 
    - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=database:${DB_PORT}
      - WAIT_TIMEOUT=60
    command: bash -c '/wait && yarn dev'

volumes:
  db-volume: