
services:
  database: 
    container_name: mysql_container
    image: mysql:5.7
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    expose: 
    - ${DB_PORT}
    ports:
      - ${DB_PORT}:3306  
    command: --default-authentication-plugin=mysql_native_password 

  api: 
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes: 
      - ./src:/app/src
    expose:
    - ${PORT}
    ports: 
    - ${PORT}:${PORT}
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_TIMEOUT=60
    command: bash -c '/wait && yarn dev'